INSERT INTO content (title, description, release_year, type, poster_path) VALUES
('Inception', 'Un ladron especializado en entrar en los suenos acepta una mision imposible para implantar una idea.', 2010, 'movie', ''),
('Breaking Bad', 'Un profesor de quimica cambia su vida para siempre cuando se involucra en el negocio de las drogas.', 2008, 'series', ''),
('Interstellar', 'Un grupo de astronautas viaja mas alla de la galaxia en busca de un nuevo hogar para la humanidad.', 2014, 'movie', ''),
('Stranger Things', 'Un pequeno pueblo queda marcado por desapariciones, experimentos secretos y una dimension aterradora.', 2016, 'series', ''),
('The Dark Knight', 'Batman enfrenta a un criminal caotico que pone en jaque a toda Gotham.', 2008, 'movie', ''),
('Game of Thrones', 'Nobles, guerreros y traidores luchan por el poder en un continente dividido.', 2011, 'series', ''),
('Avatar', 'Un exmarine llega a un mundo alienigena y termina atrapado entre dos civilizaciones.', 2009, 'movie', ''),
('The Last of Us', 'Dos sobrevivientes recorren un mundo devastado mientras buscan una ultima esperanza.', 2023, 'series', ''),
('Titanic', 'Un romance imposible nace a bordo del transatlantico mas famoso de la historia.', 1997, 'movie', ''),
('The Walking Dead', 'Un grupo de sobrevivientes intenta mantenerse con vida en medio de un apocalipsis zombi.', 2010, 'series', ''),
('Gladiator', 'Un general romano traicionado regresa como gladiador para buscar justicia.', 2000, 'movie', ''),
('The Mandalorian', 'Un cazarrecompensas solitario cruza la galaxia mientras protege a un misterioso nino.', 2019, 'series', ''),
('Mad Max: Fury Road', 'Una persecucion salvaje atraviesa el desierto en un mundo sin leyes ni agua.', 2015, 'movie', ''),
('The Boys', 'Un grupo de vigilantes enfrenta a superheroes corruptos controlados por una corporacion.', 2019, 'series', ''),
('Joker', 'Un comediante frustrado cae en una espiral de violencia y caos en Gotham.', 2019, 'movie', ''),
('Chernobyl', 'La miniserie reconstruye el desastre nuclear y las decisiones que agravaron la tragedia.', 2019, 'series', ''),
('Parasite', 'Dos familias de clases opuestas quedan unidas por una mentira que se vuelve peligrosa.', 2019, 'movie', ''),
('Dark', 'La desaparicion de un nino revela secretos familiares y una compleja red de viajes en el tiempo.', 2017, 'series', ''),
('Dune', 'El heredero de una casa noble llega al planeta mas valioso del universo y enfrenta su destino.', 2021, 'movie', ''),
('Wednesday', 'La hija de la familia Addams investiga asesinatos y secretos en una academia peculiar.', 2022, 'series', ''),
('John Wick', 'Un asesino retirado vuelve al submundo criminal tras sufrir una perdida devastadora.', 2014, 'movie', ''),
('Sherlock', 'Una version moderna del detective mas famoso del mundo y su inseparable companero.', 2010, 'series', ''),
('The Matrix', 'Un programador descubre que su realidad es una simulacion controlada por maquinas.', 1999, 'movie', ''),
('Friends', 'Seis amigos atraviesan el amor, el trabajo y la adultez en Nueva York.', 1994, 'series', ''),
('Avengers: Endgame', 'Los heroes restantes intentan revertir la derrota mas grande de su historia.', 2019, 'movie', ''),
('Better Call Saul', 'El origen de un abogado brillante y ambiguo antes de su etapa mas conocida.', 2015, 'series', ''),
('Whiplash', 'Un joven baterista entra en conflicto con un exigente e implacable instructor.', 2014, 'movie', ''),
('Black Mirror', 'Historias independientes exploran el lado mas oscuro de la tecnologia moderna.', 2011, 'series', ''),
('La La Land', 'Una actriz y un musico persiguen sus suenos mientras su relacion cambia con el exito.', 2016, 'movie', ''),
('Peaky Blinders', 'Una familia criminal intenta expandir su poder en la Birmingham de posguerra.', 2013, 'series', ''),
('Blade Runner 2049', 'Un nuevo blade runner descubre un secreto capaz de alterar el equilibrio del mundo.', 2017, 'movie', ''),
('Narcos', 'La serie sigue el ascenso y la persecucion de los grandes carteles de la droga.', 2015, 'series', ''),
('The Godfather', 'El heredero de una familia mafiosa se transforma en su lider mas temido.', 1972, 'movie', ''),
('House of the Dragon', 'La casa Targaryen se fractura por una guerra de sucesion marcada por fuego y sangre.', 2022, 'series', ''),
('Pulp Fiction', 'Historias criminales se cruzan en una narrativa llena de violencia y humor negro.', 1994, 'movie', ''),
('True Detective', 'Detectives de distintas epocas enfrentan casos que dejan marcas profundas.', 2014, 'series', ''),
('Fight Club', 'Un oficinista desencantado encuentra una salida extrema a su vacio existencial.', 1999, 'movie', ''),
('The Crown', 'La monarquia britanica es retratada a traves de conflictos politicos y personales.', 2016, 'series', ''),
('The Shawshank Redemption', 'Un hombre condenado injustamente lucha por conservar la esperanza en prision.', 1994, 'movie', ''),
('The Office', 'La rutina de una oficina comun se convierte en comedia gracias a su peculiar equipo.', 2005, 'series', ''),
('Forrest Gump', 'La vida de un hombre sencillo termina cruzandose con momentos clave de la historia reciente.', 1994, 'movie', ''),
('Loki', 'El dios del engano queda atrapado en una agencia que vigila las lineas del tiempo.', 2021, 'series', ''),
('The Lord of the Rings: The Fellowship of the Ring', 'Un grupo improbable inicia una travesia para destruir un objeto de enorme poder.', 2001, 'movie', ''),
('The Witcher', 'Un cazador de monstruos intenta sobrevivir entre guerras, magia y destinos cruzados.', 2019, 'series', ''),
('The Social Network', 'La historia del nacimiento de una red social que transformo la comunicacion global.', 2010, 'movie', ''),
('The Bear', 'Un chef vuelve a casa para salvar el negocio familiar mientras enfrenta su propio caos.', 2022, 'series', ''),
('Oppenheimer', 'La pelicula retrata el desarrollo de la bomba atomica y el peso moral de su creador.', 2023, 'movie', ''),
('Euphoria', 'Adolescentes buscan identidad y afecto mientras atraviesan excesos y heridas emocionales.', 2019, 'series', ''),
('Spider-Man: Into the Spider-Verse', 'Miles Morales descubre que no es el unico Spider-Man del multiverso.', 2018, 'movie', ''),
('Arcane', 'La rivalidad entre dos ciudades y dos hermanas desata un conflicto inolvidable.', 2021, 'series', '');
