INSERT INTO content (title, description, release_year, type, poster_path) VALUES
('Ciudad de Ceniza', 'Un detective retirado vuelve a la accion cuando una serie de incendios revela una conspiracion en el corazon de la ciudad.', 2018, 'movie', ''),
('Codigo Horizonte', 'Un equipo de analistas investiga senales imposibles que aparecen en satelites fuera de servicio.', 2019, 'series', ''),
('La Ultima Orbita', 'La tripulacion de una estacion espacial debe decidir entre regresar a la Tierra o salvar una colonia perdida.', 2021, 'movie', ''),
('Puerto Gris', 'Una periodista descubre que cada habitante del puerto oculta una version distinta del mismo crimen.', 2020, 'series', ''),
('Ecos del Titan', 'Un arqueologo descifra mensajes antiguos que pueden despertar una maquina enterrada bajo el hielo.', 2017, 'movie', ''),
('Barrio Central', 'Cinco familias enfrentan alianzas y traiciones mientras un nuevo lider intenta controlar el vecindario.', 2022, 'series', ''),
('Niebla Roja', 'Durante una evacuacion militar, una medica debe proteger a un nino con informacion decisiva.', 2016, 'movie', ''),
('Luna 7', 'La rutina de una base minera cambia cuando una senal de auxilio llega desde un tunel sellado.', 2023, 'series', ''),
('Operacion Prisma', 'Una agente encubierta se infiltra en una red internacional que trafica tecnologia experimental.', 2019, 'movie', ''),
('Casa de Cristal', 'Una dinastia poderosa lucha por mantener su imperio despues de una misteriosa desaparicion.', 2021, 'series', ''),
('Bajo la Marea', 'Un biologo marino encuentra una especie capaz de alterar el equilibrio de toda la costa.', 2015, 'movie', ''),
('Ruta 88', 'Un grupo de viajeros comparte secretos y peligros en una carretera que parece no terminar nunca.', 2020, 'series', ''),
('Proyecto Atlas', 'Dos cientificos compiten por controlar una inteligencia artificial construida para predecir guerras.', 2024, 'movie', ''),
('Doble Turno', 'Paramedicos nocturnos sobreviven al caos de la ciudad mientras lidian con sus propias cicatrices.', 2018, 'series', ''),
('Catedral del Viento', 'Un ladron profesional acepta su ultimo golpe en una fortaleza suspendida entre montanas.', 2014, 'movie', ''),
('Los Infiltrados del Sur', 'Un equipo especial se adentra en la frontera para desmantelar una organizacion invisible.', 2022, 'series', ''),
('Frontera de Sal', 'Una piloto contrabandista debe elegir entre la libertad y la familia que dejo atras.', 2017, 'movie', ''),
('Jardin Electrico', 'Ingenieros rebeldes construyen refugios autosustentables en medio de un colapso energetico.', 2023, 'series', ''),
('Sombras en Kyoto', 'Un restaurador de arte descubre un mapa oculto dentro de una pintura perseguida por criminales.', 2016, 'movie', ''),
('Distrito Delta', 'Una unidad policial experimental intenta imponer orden en un sector abandonado por el Estado.', 2021, 'series', ''),
('Manual para el Fin', 'Cuatro desconocidos reciben instrucciones anonimas para evitar una catastrofe global.', 2020, 'movie', ''),
('Bitacora 12', 'Cada episodio revela una grabacion perdida de una expedicion cientifica que nunca debio existir.', 2019, 'series', ''),
('Reyes de Acero', 'Un exboxeador vuelve al ring para enfrentar a la empresa que arruino su carrera.', 2013, 'movie', ''),
('Paralelo Norte', 'Agentes climáticos siguen la pista de sabotajes que alteran el clima en varios paises.', 2024, 'series', ''),
('La Formula del Silencio', 'Una compositora prodigio detecta patrones ocultos en una melodia prohibida.', 2018, 'movie', ''),
('Hotel Aurora', 'Los huespedes de un hotel remoto descubren que nadie puede abandonar el edificio al amanecer.', 2022, 'series', ''),
('Reloj de Arena', 'Un historiador recibe artefactos que parecen cambiar pequeños eventos del pasado.', 2015, 'movie', ''),
('Linea de Fuego', 'Bomberos y rescatistas arriesgan todo durante una temporada marcada por incendios imposibles.', 2020, 'series', ''),
('Septima Frecuencia', 'Una locutora intercepta mensajes de radio que anticipan tragedias minutos antes de ocurrir.', 2017, 'movie', ''),
('Mercado Negro', 'En una ciudad futurista, comerciantes clandestinos trafican recuerdos digitales.', 2023, 'series', ''),
('Tormenta Blanca', 'Un equipo de rescate alpino enfrenta una avalancha provocada por intereses corporativos.', 2014, 'movie', ''),
('Legado Zero', 'Herederos de una corporacion compiten por secretos ocultos en servidores fuera de linea.', 2021, 'series', ''),
('El Umbral', 'Una psicologa forense investiga casos conectados por suenos identicos entre las victimas.', 2019, 'movie', ''),
('Terminal Oeste', 'Trabajadores de una estacion ferroviaria quedan atrapados en una disputa criminal y politica.', 2018, 'series', ''),
('Mapa de Hielo', 'Exploradores urbanos descubren una ciudad subterranea bajo un glaciar en retroceso.', 2022, 'movie', ''),
('Archivo Vega', 'Un equipo de documentalistas expone proyectos secretos ligados a desapariciones masivas.', 2024, 'series', ''),
('Pacto de Noche', 'Dos enemigos se unen para sobrevivir a una persecucion que recorre toda la capital.', 2016, 'movie', ''),
('Colonia Sur', 'Pioneros y cientificos sostienen una comunidad aislada mientras una amenaza crece bajo tierra.', 2020, 'series', ''),
('Vidas Prestadas', 'Un abogado descubre que sus nuevos clientes comparten identidades fabricadas.', 2018, 'movie', ''),
('Mirador 19', 'Desde un edificio estatal, un grupo de vigilantes sigue eventos que nadie mas parece notar.', 2021, 'series', ''),
('Tren Nocturno', 'Una violinista y un exsoldado cruzan el pais persiguiendo a una sociedad secreta.', 2015, 'movie', ''),
('Fase Inicial', 'Estudiantes brillantes son reclutados para desarrollar tecnologia militar sin saberlo.', 2023, 'series', ''),
('Corazon de Neon', 'Una mecanica callejera compite en carreras ilegales para financiar una operacion urgente.', 2017, 'movie', ''),
('Costa Salvaje', 'Guardaparques, pescadores y turistas chocan cuando aparecen criaturas desconocidas en la bahia.', 2022, 'series', ''),
('Punto Ciego', 'Un fiscal obsesionado sigue una pista que lo lleva hasta la estructura mas alta del poder.', 2019, 'movie', ''),
('Origen 51', 'Cientificos y militares reabren una instalacion clausurada donde nada envejece con normalidad.', 2024, 'series', ''),
('Ciudad Vertical', 'Habitantes de una megatorre descubren que los pisos superiores esconden un experimento social.', 2020, 'movie', ''),
('Satelite Sur', 'Controladores de vuelo detectan transmisiones humanas desde un satelite oficialmente destruido.', 2021, 'series', ''),
('Memoria de Acero', 'Un ingeniero jubilado reconstruye un robot antiguo para resolver la desaparicion de su hija.', 2016, 'movie', ''),
('Nexo Urbano', 'Una red de repartidores clandestinos conecta historias, favores y conflictos en toda la metropolis.', 2023, 'series', '');
