INSERT INTO content (title, description, release_year, type, poster_path) VALUES
('The Prestige', 'Dos ilusionistas rivales llevan su obsesion por el mejor truco hasta consecuencias extremas.', 2006, 'movie', ''),
('The Sopranos', 'Un jefe mafioso intenta equilibrar el crimen organizado con su vida familiar y su terapia.', 1999, 'series', ''),
('The Departed', 'Un policia infiltrado y un topo de la mafia se buscan mutuamente dentro del mismo juego.', 2006, 'movie', ''),
('Lost', 'Los sobrevivientes de un accidente aereo descubren que la isla es mucho mas peligrosa de lo que parece.', 2004, 'series', ''),
('Se7en', 'Dos detectives siguen el rastro de un asesino serial que usa los siete pecados capitales como firma.', 1995, 'movie', ''),
('House', 'Un medico brillante y dificil resuelve los casos mas complejos con metodos poco convencionales.', 2004, 'series', ''),
('Alien', 'La tripulacion de una nave comercial se enfrenta a una criatura letal en medio del espacio.', 1979, 'movie', ''),
('Prison Break', 'Un hombre entra voluntariamente en prision para sacar a su hermano de una condena injusta.', 2005, 'series', ''),
('Aliens', 'Ripley regresa al planeta de la pesadilla acompañando a un escuadron de marines coloniales.', 1986, 'movie', ''),
('Dexter', 'Un forense especializado en sangre lleva una doble vida como asesino de criminales.', 2006, 'series', ''),
('The Silence of the Lambs', 'Una joven agente del FBI busca la ayuda de un brillante y peligroso canibal para atrapar a otro asesino.', 1991, 'movie', ''),
('Sons of Anarchy', 'Un club de motociclistas criminales protege su territorio mientras se desgarra por dentro.', 2008, 'series', ''),
('Saving Private Ryan', 'Un grupo de soldados recibe una mision imposible en plena Segunda Guerra Mundial.', 1998, 'movie', ''),
('Suits', 'Un abogado brillante sin titulo logra entrar a un estudio prestigioso ocultando su secreto.', 2011, 'series', ''),
('The Green Mile', 'Un guardia de prision conoce a un condenado con un don sobrenatural inesperado.', 1999, 'movie', ''),
('The Wire', 'La serie retrata el crimen, la politica y las instituciones de Baltimore con una mirada cruda.', 2002, 'series', ''),
('Schindler''s List', 'Un empresario oportunista termina salvando cientos de vidas durante el Holocausto.', 1993, 'movie', ''),
('Mr. Robot', 'Un hacker solitario se une a una revolucion digital contra el sistema financiero.', 2015, 'series', ''),
('The Lion King', 'Un joven leon debe asumir su lugar en el reino despues de una tragedia familiar.', 1994, 'movie', ''),
('Westworld', 'Un parque tematico futurista pierde el control de sus anfitriones artificiales.', 2016, 'series', ''),
('Toy Story', 'Los juguetes cobran vida cuando nadie los mira y enfrentan la llegada de un nuevo favorito.', 1995, 'movie', ''),
('Mindhunter', 'Dos agentes del FBI estudian asesinos seriales para entender como piensan.', 2017, 'series', ''),
('Coco', 'Un nino viaja al mundo de los muertos para descubrir la verdad sobre su familia y su musica.', 2017, 'movie', ''),
('Ozark', 'Una familia se muda a los lagos de Missouri para lavar dinero para un cartel.', 2017, 'series', ''),
('Up', 'Un viudo emprende una aventura aerea con una casa sostenida por globos y un companero inesperado.', 2009, 'movie', ''),
('The Handmaid''s Tale', 'En una dictadura teocratica, una mujer intenta sobrevivir y resistir.', 2017, 'series', ''),
('WALL-E', 'Un pequeno robot recolector de basura descubre una nueva razon para cuidar el futuro.', 2008, 'movie', ''),
('Succession', 'Una familia multimillonaria se enfrenta por el control de un imperio mediatico.', 2018, 'series', ''),
('Spirited Away', 'Una nena entra en un mundo espiritual y debe encontrar la manera de salvar a sus padres.', 2001, 'movie', ''),
('Severance', 'Empleados de una empresa separan sus recuerdos laborales y personales con un procedimiento inquietante.', 2022, 'series', ''),
('Princess Mononoke', 'Un joven guerrero queda atrapado en una lucha entre la naturaleza y la ambicion humana.', 1997, 'movie', ''),
('The White Lotus', 'Un resort de lujo sirve de escenario para tensiones, privilegios y conflictos ocultos.', 2021, 'series', ''),
('Your Name.', 'Dos adolescentes conectados por un misterio imposible cambian la vida del otro sin conocerse.', 2016, 'movie', ''),
('Fargo', 'Crimenes absurdos y personajes memorables se cruzan en historias marcadas por el frio y la violencia.', 2014, 'series', ''),
('Oldboy', 'Un hombre liberado tras anos de cautiverio busca respuestas y venganza.', 2003, 'movie', ''),
('The Americans', 'Dos espias sovieticos viven infiltrados como una familia comun en Estados Unidos.', 2013, 'series', ''),
('The Pianist', 'Un musico judio intenta sobrevivir a la destruccion de Varsovia durante la guerra.', 2002, 'movie', ''),
('Hannibal', 'Un investigador y un psiquiatra brillante desarrollan una relacion tan fascinante como peligrosa.', 2013, 'series', ''),
('The Grand Budapest Hotel', 'Las aventuras de un conserje legendario y su protegido se mezclan con un crimen y una herencia.', 2014, 'movie', ''),
('The Haunting of Hill House', 'Una familia marcada por una mansion embrujada enfrenta traumas del pasado y del presente.', 2018, 'series', ''),
('No Country for Old Men', 'Un hallazgo fortuito arrastra a varios hombres a una persecucion brutal en la frontera.', 2007, 'movie', ''),
('La Casa de Papel', 'Un grupo de delincuentes ejecuta un asalto imposible bajo el plan de un cerebro maestro.', 2017, 'series', ''),
('Prisoners', 'La desaparicion de dos nenas empuja a un padre desesperado mas alla de todos los limites.', 2013, 'movie', ''),
('Attack on Titan', 'La humanidad sobrevive detras de murallas mientras gigantes devoradores amenazan su existencia.', 2013, 'series', ''),
('Arrival', 'Una linguista intenta comunicarse con visitantes extraterrestres que llegan sin previo aviso.', 2016, 'movie', ''),
('Death Note', 'Un estudiante obtiene un cuaderno capaz de matar y decide imponer su propia justicia.', 2006, 'series', ''),
('Sicario', 'Una agente idealista entra en una guerra secreta contra el narcotrafico en la frontera.', 2015, 'movie', ''),
('Fullmetal Alchemist: Brotherhood', 'Dos hermanos alquimistas buscan recuperar lo que perdieron tras un intento prohibido.', 2009, 'series', ''),
('Her', 'Un hombre solitario establece una relacion profunda con un sistema operativo inteligente.', 2013, 'movie', ''),
('One Piece', 'Un joven pirata de goma se lanza al mar en busca del tesoro mas legendario.', 1999, 'series', ''),
('Gone Girl', 'La desaparicion de una mujer convierte a su matrimonio en un espectaculo oscuro y retorcido.', 2014, 'movie', ''),
('Bleach', 'Un adolescente obtiene poderes sobrenaturales y asume el trabajo de proteger almas y combatir monstruos.', 2004, 'series', ''),
('The Revenant', 'Un cazador dado por muerto recorre territorios salvajes decidido a sobrevivir y vengarse.', 2015, 'movie', ''),
('Vinland Saga', 'Un joven guerrero crece en medio de la guerra y la sed de venganza en tiempos vikingos.', 2019, 'series', ''),
('Logan', 'Un heroe cansado protege a una nina perseguida mientras enfrenta su ultimo gran viaje.', 2017, 'movie', ''),
('Cowboy Bebop', 'Un grupo de cazarrecompensas viaja por el espacio arrastrando viejas heridas y deudas.', 1998, 'series', ''),
('Deadpool', 'Un mercenario transforma su tragedia en una venganza irreverente y violenta.', 2016, 'movie', ''),
('Rick and Morty', 'Un cientifico brillante y desastroso arrastra a su nieto a aventuras por todo el multiverso.', 2013, 'series', ''),
('The Batman', 'Bruce Wayne investiga una serie de crimenes que revelan la corrupcion profunda de Gotham.', 2022, 'movie', ''),
('BoJack Horseman', 'Una vieja estrella de television intenta llenar el vacio de su vida entre fama, culpa y humor.', 2014, 'series', ''),
('Top Gun: Maverick', 'Un piloto legendario vuelve a entrenar a una nueva generacion para una mision de alto riesgo.', 2022, 'movie', ''),
('Brooklyn Nine-Nine', 'Detectives muy distintos comparten casos, amistad y caos en una comisaria de Nueva York.', 2013, 'series', ''),
('Mission: Impossible - Fallout', 'Ethan Hunt enfrenta una nueva crisis global cuando una operacion sale mal.', 2018, 'movie', ''),
('Parks and Recreation', 'Una funcionaria optimista intenta mejorar su ciudad con ideas imposibles y mucho entusiasmo.', 2009, 'series', ''),
('Casino Royale', 'James Bond enfrenta su primera gran prueba en una partida decisiva de poker y espionaje.', 2006, 'movie', ''),
('Community', 'Un grupo de estudiantes inadaptados convierte una universidad comunitaria en una aventura constante.', 2009, 'series', ''),
('Skyfall', 'Bond vuelve al servicio cuando el pasado de M amenaza con destruir todo a su paso.', 2012, 'movie', ''),
('Modern Family', 'Tres ramas de una familia viven situaciones cotidianas con humor, caos y carino.', 2009, 'series', ''),
('Shutter Island', 'Dos agentes investigan una desaparicion en un hospital psiquiatrico aislado.', 2010, 'movie', ''),
('How I Met Your Mother', 'Un padre le cuenta a sus hijos la larga historia de como conocio a su madre.', 2005, 'series', ''),
('Heat', 'Un policia obsesionado y un ladron profesional se enfrentan en una ciudad que no duerme.', 1995, 'movie', ''),
('Scrubs', 'Un grupo de medicos jovenes enfrenta la presion del hospital con comedia y emocion.', 2001, 'series', ''),
('Kill Bill: Vol. 1', 'Una asesina despierta del coma y comienza a tachar nombres de su lista de venganza.', 2003, 'movie', ''),
('Ted Lasso', 'Un entrenador de futbol americano llega a Inglaterra para dirigir un club sin saber casi nada del deporte.', 2020, 'series', ''),
('Inglourious Basterds', 'Un grupo de soldados judios busca sembrar terror entre los nazis en la Francia ocupada.', 2009, 'movie', ''),
('The Good Place', 'Una mujer descubre que la vida despues de la muerte tiene reglas tan absurdas como estrictas.', 2016, 'series', ''),
('Django Unchained', 'Un esclavo liberado se une a un cazador de recompensas para rescatar a su esposa.', 2012, 'movie', ''),
('Fleabag', 'Una mujer brillante e impulsiva enfrenta el dolor y el deseo con humor filoso.', 2016, 'series', ''),
('Once Upon a Time... in Hollywood', 'Un actor en decadencia y su doble viven el final de una epoca en Los Angeles.', 2019, 'movie', ''),
('Killing Eve', 'Una agente del MI5 y una asesina internacional desarrollan una peligrosa fascinacion mutua.', 2018, 'series', ''),
('The Truman Show', 'Un hombre descubre que toda su vida ha sido transmitida como un programa de television.', 1998, 'movie', ''),
('The Leftovers', 'El mundo intenta seguir adelante despues de una desaparicion global sin explicacion.', 2014, 'series', ''),
('Eternal Sunshine of the Spotless Mind', 'Una pareja recorre sus recuerdos mientras intenta borrarse mutuamente de la memoria.', 2004, 'movie', ''),
('Boardwalk Empire', 'Politica, crimen y negocios se mezclan durante la ley seca en Atlantic City.', 2010, 'series', ''),
('Back to the Future', 'Un adolescente viaja accidentalmente al pasado y pone en riesgo su propia existencia.', 1985, 'movie', ''),
('Band of Brothers', 'La miniserie sigue a una compania de paracaidistas desde el entrenamiento hasta el fin de la guerra.', 2001, 'series', ''),
('Jurassic Park', 'Un parque con dinosaurios clonados se convierte rapidamente en una trampa mortal.', 1993, 'movie', ''),
('The Pacific', 'La guerra en el frente del Pacifico es contada desde la experiencia de varios marines.', 2010, 'series', ''),
('The Sixth Sense', 'Un psicologo infantil atiende a un nino que afirma ver personas muertas.', 1999, 'movie', ''),
('Mr. Bean', 'El torpe y silencioso protagonista convierte cualquier situacion cotidiana en un desastre inolvidable.', 1990, 'series', ''),
('A Quiet Place', 'Una familia sobrevive en silencio absoluto mientras criaturas letales cazan por el sonido.', 2018, 'movie', ''),
('Avatar: The Last Airbender', 'Un joven maestro del aire debe restaurar el equilibrio entre naciones en guerra.', 2005, 'series', ''),
('Get Out', 'La visita a la familia de una novia revela un horror tan elegante como perturbador.', 2017, 'movie', ''),
('Daredevil', 'Un abogado ciego combate el crimen de noche con una intensidad brutal.', 2015, 'series', ''),
('The Conjuring', 'Dos investigadores paranormales afrontan uno de los casos mas aterradores de su carrera.', 2013, 'movie', ''),
('Jessica Jones', 'Una detective con fuerza sobrehumana enfrenta traumas y amenazas de su pasado.', 2015, 'series', ''),
('Ford v Ferrari', 'Dos visionarios del automovilismo intentan vencer a Ferrari en la carrera mas exigente del mundo.', 2019, 'movie', ''),
('Andor', 'La serie sigue la radicalizacion de un hombre comun dentro de la rebelion contra el Imperio.', 2022, 'series', ''),
('Knives Out', 'Un detective investiga la muerte de un escritor rodeado de familiares sospechosos.', 2019, 'movie', ''),
('The Penguin', 'El ascenso criminal de Oz Cobb transforma el submundo de Gotham tras una gran caida del poder.', 2024, 'series', '');
